<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class EmployeeSeeder extends Seeder
{
    public function run(): void
    {
        // Ambil religion_id Islam
        $religionId = DB::table('t_religions')->where('name', 'Islam')->value('id');

        // Ambil semua posisi dari tabel
        $positionIds = DB::table('t_positions')->pluck('id', 'position_name')->toArray();

        // Data employees (25 data)
        $employees = [
            [
                'employee_number' => '12130569001',
                'full_name' => 'Saifulloh Rifai',
                'birth_place' => 'Banjarnegara',
                'address' => 'Jl. Melon No.16 Dian Asri',
                'birth_date' => '1968-03-15',
                'gender' => 'M',
                'rank' => 'IV/e',
                'echelon' => 'I',
                'position_name' => 'Kepala Sekretariat Utama',
                'workplace' => 'Jakarta',
                'phone_number' => null,
                'tax_number' => null,
            ],
            [
                'employee_number' => null,
                'full_name' => null,
                'birth_place' => null,
                'address' => 'Jl. Golf Komp Bakosurtanal No.39',
                'birth_date' => '1968-08-27',
                'gender' => 'M',
                'rank' => 'IV/a',
                'echelon' => null,
                'position_name' => 'Penyusun laporan keuangan',
                'workplace' => null,
                'phone_number' => null,
                'tax_number' => null,
            ],
            [
                'employee_number' => null,
                'full_name' => null,
                'birth_place' => null,
                'address' => 'Jl.Mendut III, Puri Nirwana I RT.03/16',
                'birth_date' => '1987-07-10',
                'gender' => 'M',
                'rank' => 'III/c',
                'echelon' => null,
                'position_name' => 'Surveyor Pemetaan Pertama',
                'workplace' => null,
                'phone_number' => null,
                'tax_number' => null,
            ],
            [
                'employee_number' => null,
                'full_name' => null,
                'birth_place' => null,
                'address' => 'Perum Jombor Baru',
                'birth_date' => '1987-05-03',
                'gender' => 'M',
                'rank' => 'III/b',
                'echelon' => null,
                'position_name' => 'Analis Data Survei dan Pemetaan',
                'workplace' => null,
                'phone_number' => null,
                'tax_number' => null,
            ],
            [
                'employee_number' => null,
                'full_name' => null,
                'birth_place' => 'Trengalek',
                'address' => 'Trengalek',
                'birth_date' => '1992-07-07',
                'gender' => 'M',
                'rank' => 'III/a',
                'echelon' => null,
                'position_name' => 'Perancang Per-UUan Utama',
                'workplace' => null,
                'phone_number' => null,
                'tax_number' => null,
            ],
            [
                'employee_number' => null,
                'full_name' => null,
                'birth_place' => null,
                'address' => 'Bella Casa Residence Blok E.1 No.9',
                'birth_date' => '1963-06-05',
                'gender' => 'M',
                'rank' => 'IV/c',
                'echelon' => 'II',
                'position_name' => 'Kepala Biro Perencanaan, Kepegawaian dan',
                'workplace' => null,
                'phone_number' => null,
                'tax_number' => null,
            ],
            [
                'employee_number' => null,
                'full_name' => null,
                'birth_place' => null,
                'address' => 'Jl Pelita I/18 Kedung Halang Talang',
                'birth_date' => '1952-11-07',
                'gender' => 'M',
                'rank' => 'IV/e',
                'echelon' => null,
                'position_name' => 'Widyaiswara Utama',
                'workplace' => null,
                'phone_number' => null,
                'tax_number' => null,
            ],
            [
                'employee_number' => null,
                'full_name' => null,
                'birth_place' => null,
                'address' => 'Komp. BAKOSURTANAL CIKARET',
                'birth_date' => '1954-09-12',
                'gender' => 'M',
                'rank' => 'IV/e',
                'echelon' => null,
                'position_name' => null,
                'workplace' => null,
                'phone_number' => null,
                'tax_number' => null,
            ],
            [
                'employee_number' => null,
                'full_name' => null,
                'birth_place' => null,
                'address' => 'Cigadung Selatan II/135',
                'birth_date' => '1966-11-30',
                'gender' => 'M',
                'rank' => 'IV/d',
                'echelon' => null,
                'position_name' => null,
                'workplace' => null,
                'phone_number' => null,
                'tax_number' => null,
            ],
            [
                'employee_number' => null,
                'full_name' => null,
                'birth_place' => null,
                'address' => 'Jl Raya Tegar Beriman Gg H Jairan No 116',
                'birth_date' => '1962-12-04',
                'gender' => 'M',
                'rank' => 'IV/c',
                'echelon' => null,
                'position_name' => 'Analis Kepegawaian Madya',
                'workplace' => null,
                'phone_number' => null,
                'tax_number' => null,
            ],
            [
                'employee_number' => null,
                'full_name' => null,
                'birth_place' => null,
                'address' => null,
                'birth_date' => '1963-07-03',
                'gender' => 'M',
                'rank' => 'IV/b',
                'echelon' => null,
                'position_name' => null,
                'workplace' => null,
                'phone_number' => null,
                'tax_number' => null,
            ],
            [
                'employee_number' => null,
                'full_name' => null,
                'birth_place' => null,
                'address' => 'Jl.Kupu-kupu Blok NJ 16. RT.03/09',
                'birth_date' => '1970-08-22',
                'gender' => 'M',
                'rank' => 'IV/a',
                'echelon' => null,
                'position_name' => 'Kepala Sub Bidang Kerjasama dan Pelayanan Riset, DKP',
                'workplace' => null,
                'phone_number' => null,
                'tax_number' => null,
            ],
            [
                'employee_number' => null,
                'full_name' => null,
                'birth_place' => null,
                'address' => 'Kp. Sawah RT.01/11 No.27',
                'birth_date' => '1958-10-11',
                'gender' => 'M',
                'rank' => 'III/d',
                'echelon' => null,
                'position_name' => 'Analis Hukum',
                'workplace' => null,
                'phone_number' => null,
                'tax_number' => null,
            ],
            [
                'employee_number' => null,
                'full_name' => null,
                'birth_place' => null,
                'address' => 'Jl. Kebon Pedes Gang Pacilong No. 4',
                'birth_date' => '1967-12-14',
                'gender' => 'M',
                'rank' => 'III/c',
                'echelon' => null,
                'position_name' => 'Peneliti Pertama',
                'workplace' => null,
                'phone_number' => null,
                'tax_number' => null,
            ],
            [
                'employee_number' => null,
                'full_name' => null,
                'birth_place' => null,
                'address' => 'Jl Setasiun No 294 RT 06 RW 01',
                'birth_date' => '1983-04-09',
                'gender' => 'M',
                'rank' => 'III/c',
                'echelon' => null,
                'position_name' => 'Surveyor Pemetaan Muda',
                'workplace' => null,
                'phone_number' => null,
                'tax_number' => null,
            ],
            [
                'employee_number' => null,
                'full_name' => null,
                'birth_place' => null,
                'address' => 'Perum Delivina Blok A.4/6',
                'birth_date' => '1983-08-04',
                'gender' => 'M',
                'rank' => 'III/c',
                'echelon' => null,
                'position_name' => 'Surveyor Pemetaan Muda',
                'workplace' => null,
                'phone_number' => null,
                'tax_number' => null,
            ],
            [
                'employee_number' => null,
                'full_name' => null,
                'birth_place' => null,
                'address' => 'Jln.Golf Ling. 2 Citatah Dalam No.21',
                'birth_date' => '1962-08-14',
                'gender' => 'M',
                'rank' => 'III/c',
                'echelon' => null,
                'position_name' => 'Surveyor Pemetaan Muda',
                'workplace' => null,
                'phone_number' => null,
                'tax_number' => null,
            ],
            [
                'employee_number' => null,
                'full_name' => null,
                'birth_place' => null,
                'address' => 'Jl. Ciliwung BCE RT.07/11',
                'birth_date' => '1973-02-21',
                'gender' => 'M',
                'rank' => 'III/c',
                'echelon' => null,
                'position_name' => 'Surveyor Pemetaan Muda',
                'workplace' => null,
                'phone_number' => null,
                'tax_number' => null,
            ],
            [
                'employee_number' => null,
                'full_name' => null,
                'birth_place' => null,
                'address' => 'Kp. Kandang',
                'birth_date' => '1974-04-29',
                'gender' => 'M',
                'rank' => 'III/c',
                'echelon' => null,
                'position_name' => 'Surveyor Pemetaan Muda',
                'workplace' => null,
                'phone_number' => null,
                'tax_number' => null,
            ],
            [
                'employee_number' => null,
                'full_name' => null,
                'birth_place' => null,
                'address' => 'Jl. Garuda Gg. Mangga RT002',
                'birth_date' => '1975-12-28',
                'gender' => 'M',
                'rank' => 'III/c',
                'echelon' => null,
                'position_name' => 'Analis Jabatan',
                'workplace' => null,
                'phone_number' => null,
                'tax_number' => null,
            ],
            [
                'employee_number' => null,
                'full_name' => null,
                'birth_place' => null,
                'address' => 'Perum Puri Karadenan Blok C 7',
                'birth_date' => '1979-03-26',
                'gender' => 'M',
                'rank' => 'III/c',
                'echelon' => null,
                'position_name' => 'Surveyor Pemetaan Muda',
                'workplace' => null,
                'phone_number' => null,
                'tax_number' => null,
            ],
            [
                'employee_number' => null,
                'full_name' => null,
                'birth_place' => null,
                'address' => 'Jl. Satsiun No.225 RT.02/02',
                'birth_date' => '1979-06-12',
                'gender' => 'M',
                'rank' => 'III/c',
                'echelon' => null,
                'position_name' => null,
                'workplace' => null,
                'phone_number' => null,
                'tax_number' => null,
            ],
            [
                'employee_number' => null,
                'full_name' => null,
                'birth_place' => null,
                'address' => 'Jl. Prambanan RT.12/16 Pabuaran',
                'birth_date' => '1980-01-11',
                'gender' => 'M',
                'rank' => 'III/c',
                'echelon' => null,
                'position_name' => 'Surveyor Pemetaan Muda',
                'workplace' => null,
                'phone_number' => null,
                'tax_number' => null,
            ],
            [
                'employee_number' => null,
                'full_name' => null,
                'birth_place' => null,
                'address' => 'Duta parahiyanganBlok AB 72',
                'birth_date' => '1977-02-07',
                'gender' => 'M',
                'rank' => 'III/c',
                'echelon' => null,
                'position_name' => 'Surveyor Pemetaan Muda',
                'workplace' => null,
                'phone_number' => null,
                'tax_number' => null,
            ],
            [
                'employee_number' => null,
                'full_name' => null,
                'birth_place' => null,
                'address' => null,
                'birth_date' => '1980-03-06',
                'gender' => 'F',
                'rank' => 'III/c',
                'echelon' => null,
                'position_name' => 'Kepala Subbag Kepegawaian',
                'workplace' => null,
                'phone_number' => null,
                'tax_number' => null,
            ],
        ];

        foreach ($employees as $emp) {
            $employeeId = DB::table('t_employees')->insertGetId([
                'employee_number' => $emp['employee_number'],
                'full_name' => $emp['full_name'],
                'birth_place' => $emp['birth_place'],
                'address' => $emp['address'],
                'birth_date' => $emp['birth_date'] ? Carbon::parse($emp['birth_date'])->format('Y-m-d') : null,
                'gender' => $emp['gender'],
                'religion_id' => $religionId,
                'created_at' => now(),
                'updated_at' => now(),
            ]);

            DB::table('t_employee_details')->insert([
                'employee_id' => $employeeId,
                'position_id' => $emp['position_name'] ? $positionIds[$emp['position_name']] : null,
                'work_unit_id' => null,
                'rank' => $emp['rank'],
                'echelon' => $emp['echelon'],
                'workplace' => $emp['workplace'],
                'phone_number' => $emp['phone_number'],
                'tax_number' => $emp['tax_number'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
